blank_issues_enabled: false
contact_links:
  - name: üìö –î–æ–∫—É–º–µ–Ω—Ç–∞—Ü–∏—è
    url: https://aioyookassa.readthedocs.io/en/latest/
    about: –û–∑–Ω–∞–∫–æ–º—å—Ç–µ—Å—å —Å –¥–æ–∫—É–º–µ–Ω—Ç–∞—Ü–∏–µ–π –ø–µ—Ä–µ–¥ —Å–æ–∑–¥–∞–Ω–∏–µ–º Issue
  - name: üí¨ Telegram
    url: https://t.me/masaasibaata
    about: –°–≤—è–∂–∏—Ç–µ—Å—å —Å —Ä–∞–∑—Ä–∞–±–æ—Ç—á–∏–∫–æ–º –¥–ª—è –≤–æ–ø—Ä–æ—Å–æ–≤ –∏ –æ–±—Å—É–∂–¥–µ–Ω–∏–π

